import { VisualTheme } from './types';

export const THEMES: Record<string, VisualTheme> = {
  midnight: {
    id: 'midnight',
    name: 'Midnight Dark',
    bgClass: 'bg-slate-950 text-slate-100',
    slideBgClass: 'bg-slate-900 border-slate-800 text-slate-100',
    borderClass: 'border-slate-800',
    accentColor: 'indigo',
    accentHex: '#6366f1',
    secondaryHex: '#0ea5e9',
    textTitleClass: 'font-sans font-bold text-3xl tracking-tight text-white',
    textSubtitleClass: 'font-sans text-sm text-indigo-400 font-medium uppercase tracking-wider',
    textBodyClass: 'font-sans text-slate-300 leading-relaxed text-sm md:text-base',
    fontFamily: 'font-sans',
    badgeClass: 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/20',
    accentBg: 'bg-indigo-600 hover:bg-indigo-500',
    glowEffect: 'shadow-[0_0_15px_rgba(99,102,241,0.15)]',
  },
  emerald: {
    id: 'emerald',
    name: 'Emerald Minimalist',
    bgClass: 'bg-stone-50 text-stone-900',
    slideBgClass: 'bg-white border-stone-200 text-stone-900 shadow-sm',
    borderClass: 'border-stone-200',
    accentColor: 'emerald',
    accentHex: '#10b981',
    secondaryHex: '#78716c',
    textTitleClass: 'font-serif font-semibold text-3xl tracking-tight text-stone-900',
    textSubtitleClass: 'font-sans text-xs text-emerald-700 font-semibold uppercase tracking-widest',
    textBodyClass: 'font-sans text-stone-600 leading-relaxed text-sm md:text-base',
    fontFamily: 'font-serif',
    badgeClass: 'bg-emerald-50 text-emerald-700 border border-emerald-100',
    accentBg: 'bg-emerald-800 hover:bg-emerald-700 text-white',
    glowEffect: 'shadow-[0_4px_20px_rgba(16,185,129,0.05)]',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    bgClass: 'bg-black text-fuchsia-400 font-mono',
    slideBgClass: 'bg-zinc-950 border-fuchsia-500/50 text-zinc-100',
    borderClass: 'border-fuchsia-500/30',
    accentColor: 'fuchsia',
    accentHex: '#d946ef',
    secondaryHex: '#22c55e',
    textTitleClass: 'font-mono font-black text-3xl tracking-tighter text-white uppercase italic',
    textSubtitleClass: 'font-mono text-xs text-cyan-400 font-bold uppercase tracking-widest blink',
    textBodyClass: 'font-mono text-zinc-300 leading-relaxed text-xs md:text-sm',
    fontFamily: 'font-mono',
    badgeClass: 'bg-fuchsia-950/40 text-fuchsia-400 border border-fuchsia-500/30',
    accentBg: 'bg-fuchsia-600 hover:bg-fuchsia-500 text-black font-black',
    glowEffect: 'shadow-[0_0_20px_rgba(217,70,239,0.25)] border-fuchsia-500',
  },
  royal: {
    id: 'royal',
    name: 'Royal Purple',
    bgClass: 'bg-purple-950 text-purple-100',
    slideBgClass: 'bg-gradient-to-br from-purple-900 to-indigo-950 border-purple-800/40 text-purple-100',
    borderClass: 'border-purple-800/40',
    accentColor: 'amber',
    accentHex: '#f59e0b',
    secondaryHex: '#ec4899',
    textTitleClass: 'font-serif italic font-extrabold text-3xl text-amber-100',
    textSubtitleClass: 'font-sans text-xs text-amber-400 font-bold uppercase tracking-widest',
    textBodyClass: 'font-sans text-purple-200 leading-relaxed text-sm md:text-base',
    fontFamily: 'font-serif',
    badgeClass: 'bg-amber-400/10 text-amber-300 border border-amber-400/20',
    accentBg: 'bg-amber-500 hover:bg-amber-400 text-purple-950 font-bold',
    glowEffect: 'shadow-[0_8px_30px_rgba(245,158,11,0.1)]',
  },
};
